version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: pip install --user nox
      - run: nox

      - store_artifacts:
          path: test-reports
          destination: test-reports